### ISSUE TITLE
Headless Mode - Exporting Auto-Manifest

### ISSUE THREAD

**Issue by Kir-Latyshev** [space-logistics-org/spacenet-java#80]
Add another headless functionality into the Java code that would, apart from computing demands, also run the Auto-Manifest algorithm and return the resulting manifest. If it is too cumbersome to have a separate JSON structure for the manifest, it can be returned in the same text format it is now exported in in the GUI (the Export Manifest block on the Manifest tab).

Also, I noticed that the Export Manifest block currently exports only items that were manifested but does not export any details for items that were packed but failed to be manifested. If it is not difficult, can those be extracted as well for the headless functionality? Either within the same manifest structure (e.g., with the flight ids empty) or as a separate block of data - whatever is simpler.

**Comment by ptgrogan** [comment]
I added a new headless command `auto-manifest` that runs and outputs the manifesting output. It has a similar command line interface as the previous demands analysis but does not duplicate the outputs (we could revisit if necessary).

It was easier to develop a new JSON output format rather than reusing the CSV format on the manifesting tab. The resulting output file has the following structure:

ManifestAnalysis:
* containers : List<ManifestContainer> (list of all packed containers)
* actions : List<ManifestAction> (list of all manifesting actions, i.e., manifested containers)
* gaps : List<ManifestGap> (list of all manifesting gaps, i.e., unmanifested containers)

ManifestContainer:
* environment : String (pressurized/unpressurized)
* mass : Double (empty container mass)
* volume : Double (empty container volume)
* cargoEnvironment : String (pressurized/unpressurized)
* maxCargoMass : Double (max container contents mass)
* maxCargoVolume : Double (max container contents volume)
* packedMass : Double (total packed container contents mass)
* packedVolume : Double (total packed container contents volume)
* packedDemands : List<ManifestDemand> (packed contents)

ManifestDemand:
* resource : ResourceType (type of resource demand)
* amount : Double (amount of resource demand)
* mass : Double (mass of resource demand)
* volume : Double (volume of resource demand)
* node : Location (location of resource demand, assigned to a "supply point")
* time : Double (time of resource demand, assigned to a "supply point"

ResourceType: (same as previous demands analysis outputs)
* type : String
* name : String
* classOfSupply : Integer
* environment : String
* units : String
* unitMass : Double
* unitVolume : Double
* packingFactor : Double

Location: (same as previous demands analysis output)
* id : Integer
* name : String

ManifestAction:
* time : Double (time of manifesting action, resolves to the start time of a "supply edge")
* node : Location (location of the manifesting action, resolves to the origin of a "supply edge")
* carriers : List<ManifestCarrier> (list of carriers participating in the supply edge, even if no containers are manifested)

ManifestCarrier:
* environment : String (pressurized/unpressurized)
* mass : Double (empty carrier mass)
* volume : Double (empty carrier volume)
* cargoEnvironment : String (pressurized/unpressurized)
* maxCargoMass : Double (max carrier contents mass)
* maxCargoVolume : Double (max carrier contents volume)
* manifestedMass : Double (total manifested carrier contents mass)
* manifestedVolume : Double (total manifested carrier contents volume)
* manifestedContainers : List<ManifestedContainer> (list of manifested containers)

Give it a try and suggest any desired interface modifications.
